[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.12.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
