[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.12.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://sei23-staging.herokuapp.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://sei23-staging.herokuapp.com"
