[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.12.0"

[functions]
  included_files = [
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/router-context*",
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
